### ISSUE TITLE
Oreilly and Addison-Westley books

### ISSUE THREAD

**Issue by gtani7** [dariubs/GoBooks#11]
there could be another tabs for not yet released books by Kernighan and from Oreilly:

http://www.amazon.com/Programming-Language-Addison-Wesley-Professional-Computing/dp/0134190440/

http://www.amazon.com/Go-Up-Running-Alan-Harris/dp/144937025X/

**Comment by nathany** [comment]
Unfortunately Go Up And Running was cancelled. See #10.

The publisher link for Donovan & Kernighan's book is:
http://www.informit.com/store/go-programming-language-9780134190440

**Comment by nathany** [comment]
This can be closed with #18.
