### ISSUE TITLE
Removing Mastering Concurrency in Go?

### ISSUE THREAD

**Issue by razorSharpDull** [dariubs/GoBooks#111]
Reviews on [some](https://www.goodreads.com/en/book/show/22861382-mastering-concurrency-in-go)  [websites](https://www.amazon.ca/Mastering-Concurrency-Go-Nathan-Kozyra/dp/1783983485) state that [Mastering Concurrency in Go by Nathan Kozyra](https://github.com/dariubs/GoBooks#mastering-concurrency-in-go)  is poorly written, with examples that include errors, race conditions, etc., which ultimately makes this a misinforming or general unproductive resource. I wonder if it would be best to remove this from the list

**Comment by nathany** [comment]
I'm not sure if this list is intended to be curated like that.

@dariubs

**Comment by razorSharpDull** [comment]
It would be a pain to have to vet every book to some standard, I'm with you on that. But this book in particular provides content that is so antithetical to its purpose (first code I tested immediately deadlocked!) that it really shouldn't be on _any_ recommended Go book list, let alone Awesome Go books.

**Comment by nathany** [comment]
That is a fair point -- if we're going to call this list "Awesome Go Books" -- then perhaps it shouldn't include books with 2-star ratings on Amazon.

Checking when it was added to the list, @dariubs added it ~7 years ago. Today there are several other books for learning concurrency.

@razorSharpDull Would you be willing to open a pull request to remove it?

Thus far we haven't done any vetting as to whether or not a book is "awesome" -- just allowed any Go-related books into the list. I don't think that will change.

**Comment by nathany** [comment]
#135 removes Mastering Concurrency in Go on the basis of being obsolete (before 2018) 

rather than based on a review score
