### ISSUE TITLE
Scam website URL in README.md

### ISSUE THREAD

**Issue by mandriota** [dariubs/GoBooks#136]
This site (https://webia.io/topic/golang-learning-resources) randomly redirects me to McAfee scam site or offers me to turn on push notifications
https://github.com/dariubs/GoBooks/assets/62650188/3f62f91f-6217-46a1-8c49-d3b53fee2e10

<img width="1440" alt="screenshot 31" src="https://github.com/dariubs/GoBooks/assets/62650188/87ec88b2-d806-4a23-9a34-647638874a6f">
<img width="1440" alt="screenshot 32" src="https://github.com/dariubs/GoBooks/assets/62650188/6563a172-42e4-43b8-ad30-62d30279d54c">

**Comment by nathany** [comment]
Thanks for taking the time to report the issue. I've removed it from the README.

It's quite possible that the link/domain changed at some point, as some of these links were added many years ago.
