### ISSUE TITLE
Link for 'The Little Go Book' is wrong

### ISSUE THREAD

**Issue by joxz** [dariubs/GoBooks#31]
Maybe the link has changed. Working link: [http://openmymind.net/assets/go/go.pdf](http://openmymind.net/assets/go/go.pdf)

**Comment by appleboy** [comment]
Where is the wrong link?

**Comment by joxz** [comment]
https://github.com/dariubs/GoBooks#the-little-go-book-free
right in the title

**Comment by nathany** [comment]
Okay. Thanks.
