### ISSUE TITLE
Go wiki

### ISSUE THREAD

**Issue by nathany** [dariubs/GoBooks#4]
Nice work. There is also a list in the Go wiki at https://github.com/golang/go/wiki/Books though you have a few that aren't listed there.

Anyone can contribute to the Go Wiki if you'd like to add a few books or add the book covers.

**Comment by dariubs** [comment]
Anyone can add the covers and titles from here to golang docs But this repo has a different aproach. Sort Free or Open-Source books first, Not just the publication date ;-)
