### ISSUE TITLE
Remove Build Webapps in Go Download links

### ISSUE THREAD

**Issue by Oxyrus** [dariubs/GoBooks#40]
The book is no longer available to download: https://github.com/dariubs/GoBooks#build-webapps-in-go-the-anti-textbook-free

* https://www.gitbook.com/download/pdf/book/thewhitetulip/webapp-with-golang-anti-textbook
* https://www.gitbook.com/download/epub/book/thewhitetulip/webapp-with-golang-anti-textbook
* https://www.gitbook.com/download/mobi/book/thewhitetulip/webapp-with-golang-anti-textbook

> 404
Not Found
E-Books downloads have been disabled for this book

**Comment by nathany** [comment]
Thanks for the report. It looks like it has moved from GitBook to Leanpub: https://leanpub.com/antitextbookGo/
