### ISSUE TITLE
Books to add

### ISSUE THREAD

**Issue by dgryski** [dariubs/GoBooks#46]
* [x] Concurrency in Go http://shop.oreilly.com/product/mobile/0636920046189.do?sortby=bestSellers by @kat-co

**Comment by nathany** [comment]
pull requests welcome 😉

**Comment by nathany** [comment]
* [ ] Black Hat Go https://www.nostarch.com/blackhatgo

**Comment by nathany** [comment]
* [ ] Go programming language secure coding practices guide https://github.com/Checkmarx/Go-SCP
