### ISSUE TITLE
Add the version of golang that the book supports

### ISSUE THREAD

**Issue by anjanb** [dariubs/GoBooks#77]
golang is more stable, as compared to other languages; However, there are still changes to the development environment, features, capabilities. So, it helps a lot of know which version of golang the book targets or supports. It would also help to know which year the book was published.

**Comment by nathany** [comment]
That's a great idea, but I'm not sure where we would get that information.

https://github.com/golang/go/wiki/Books does include publication dates though, so that may help

**Comment by atc0005** [comment]
> I'm not sure where we would get that information

If split into some sort of punch list, it might be feasible to have someone with access to a subscription service lookup those details. I don't have the free time to process a large list by myself, but I could help out by looking up the info for any books that I have previously purchased. Others may be willing to do the same.

**Comment by nathany** [comment]
Perhaps we could, but I just don't know how valuable it is to try to find Go versions.

As an example, the book I wrote came out in 2018 when [go 1.10](https://golang.org/doc/devel/release.html) was out. Updating CI today to the latest Go 1.16 rc1 reveals that everything still works unmodified, as it should.

If other books have any issues, it's more than likely related to third-party libraries than the Go version itself, or typos in the book source code, or maybe still requiring a GOPATH.

The publication date would be nice to include, but I'm not convinced that digging up the Go version adds anything that can't be derived from the publication date.

**Comment by atc0005** [comment]
> @nathany: The publication date would be nice to include

Agreed. Worst case that could be added now, then the related Go version later if desired. 

I don't have the time to drive this forward, but I could help locate the publication date of some titles if someone else were to start the effort.

**Comment by nathany** [comment]
#111 removes books older than 2018 and indicates the year they were published
