### ISSUE TITLE
Golang for DevOps

### ISSUE THREAD

**Issue by dpthegrey** [dariubs/GoBooks#89]
I am looking for a book which explains using go for DevOps workflow as mentioned in [roadmap.sh](https://roadmap.sh/devops) that if a person has to pursue building tools in DevOps using Golang or which explains the use-case of golang in DevOps ecosystem then what they should refer or any kind of resource as Golang is good in systems programming.  I feel like there should be a section for DevOps in this heaven of GoBooks for everyone to learn. What do you people think? Let me know your suggestions. Thanks.

**Comment by a8171** [comment]
"Cloud Native Go" Could be a good book for building Cloudnative Application and deploying them. But specifically if you want to develop the DevOps tools using Golang, then "Go : Building DevOps Tools" By Matthew Spaulding could be a good choice.

**Comment by dpthegrey** [comment]
Actually I meant any guidance of using go for DevOps. No specifically building tools but how a person should approach after knowing go is what they need to learn for DevOps as per [roadmap.sh ](https://roadmap.sh/devops)

**Comment by nathany** [comment]
I'd suggest asking on the golang-nuts mailing list or one of the other forums: https://golang.org/help/
